from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import DATABASE_URL
from app.db.database import Base

# Import every model so SQLAlchemy registers every table in Base.metadata.
from app.models.chat import Chat  # noqa: F401
from app.models.chat_history import ChatHistory  # noqa: F401
from app.models.medical_image import MedicalImage  # noqa: F401
from app.models.message import Message  # noqa: F401
from app.models.quick_response import QuickResponse  # noqa: F401
from app.models.report import Report  # noqa: F401
from app.models.summary import Summary  # noqa: F401
from app.models.upload_session import UploadSession  # noqa: F401
from app.models.user import User  # noqa: F401


config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)

# Never store credentials in alembic.ini. Use the same backend/.env as FastAPI.
config.set_main_option("sqlalchemy.url", DATABASE_URL.replace("%", "%%"))
target_metadata = Base.metadata


def include_object(object_, name, type_, reflected, compare_to):
    """Adopt the populated pre-Alembic database without destructive cleanup.

    This project had legacy helper tables/columns before Alembic was added.
    They may still contain internship test data and are intentionally retained.
    Alembic continues to detect new ORM tables and columns, while avoiding
    autogenerated DROP operations or constraint/type rewrites for adopted
    legacy objects. A reviewed data migration can retire them later.
    """
    if reflected and compare_to is None and type_ in {"table", "column", "index"}:
        return False
    # For an existing column Alembic can invoke this callback with either the
    # reflected object or the model object as ``object_``. Skip alterations in
    # both directions, but continue including genuinely new model columns
    # (compare_to is None and reflected is False).
    if type_ == "column" and compare_to is not None:
        return False
    if type_ == "index" and not reflected and name and name.endswith("_id"):
        columns = list(getattr(object_, "columns", []))
        if len(columns) == 1 and columns[0].name == "id":
            return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
